name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Build with Gradle (sem wrapper)
        run: gradle assembleRelease bundleRelease

      - name: Firebase App Distribution
        uses: w9jds/firebase-action@v13.35.1
        with:
          args: appdistribution:distribute app/build/outputs/apk/release/*.apk --app com.heavy.studio --testers "dev-team@example.com, qa@example.com" --release-notes "Nova versão automatizada via CI/CD"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab
